name: TurfWars
api: 1.12.0
version: InDEV
main: tufwars\tw\Main
load: POSTWORLD
author: EmreTr1
website: not found


commands:
 turfwars:
  permission: tufwars.command.tw
  description: TurfWars Main Command
  usage: /tw <join|remove|create|leave|help>
