name: TheQuiver
main: TheQuiver\Main
version: 1.0.3
api: [1.0.0]
load: POSTWORLD
author: EmreTr1
commands:
 tq:
  permission: TheQuiver.command.fsg
  description: TheQuiver
  usage: /tq <set|remove>
 lobby:
  permission: TheQuiver.command.lobby
  description: lobiye doner
  usage: /lobby
permissions:
 TheQuiver.*:
  description: hepsi
  default: false
  children:
   TheQuiver.command.*:
    description: cocuk
    default: false
    children:
     TheQuiver.command.lobby:
      description: lobi ye doner
      default: true
     TheQuiver.command.fsg:
      description: TheQuiver
      default: op
   TheQuiver.touch.startgame:
    description: TheQuiver
    default: true
